name: Run test with cicd

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_api_automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test with pytest
        run: pytest Test/ -v
        env:
          WEBHOOK_SLACK: ${{ secrets.WEBHOOK_SLACK }}
          QASE_IO_TOKEN: ${{ secrets.QASE_IO_TOKEN }}


      - name: Deploy to Netlify
        if: always()
        id: deployment-netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./report"
          github-token: ${{ secrets.MY_TOKEN_GITHUB }}
          deploy-message: "Deploy pytest reporter from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 20

      - name: Send Report Slack
        run: python setting/slack_notification.py
        env:
        WEBHOOK_SLACK: ${{ secrets.WEBHOOK_SLACK }}